// <auto-generated />
namespace PlataformaRio2C.Infra.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdateModelSprint2MiniBioAndSocialMediaAndTradeNameAndUserUseTerm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateModelSprint2MiniBioAndSocialMediaAndTradeNameAndUserUseTerm));
        
        string IMigrationMetadata.Id
        {
            get { return "201710192001220_UpdateModelSprint2MiniBioAndSocialMediaAndTradeNameAndUserUseTerm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
