// <auto-generated />
namespace PlataformaRio2C.Infra.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddConferenceAndLecturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConferenceAndLecturer));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011903051_AddConferenceAndLecturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
