//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaRio2C.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlataformaRio2C.Infra.CrossCutting.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Acesso negado..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço obrigatório..
        /// </summary>
        public static string AddressIsRequired {
            get {
                return ResourceManager.GetString("AddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atenção! Você selecionou somente {0} players de {1} possíveis..
        /// </summary>
        public static string AttentionPossiblePlayersNotSelected {
            get {
                return ResourceManager.GetString("AttentionPossiblePlayersNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do crachá obrigatório..
        /// </summary>
        public static string BadgeIsRequired {
            get {
                return ResourceManager.GetString("BadgeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível editar um projeto submetido para avaliação de player.
        /// </summary>
        public static string CanNotEditASubmittedProjectForPlayerEvaluation {
            get {
                return ResourceManager.GetString("CanNotEditASubmittedProjectForPlayerEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade inválida..
        /// </summary>
        public static string CityIsInvalid {
            get {
                return ResourceManager.GetString("CityIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade obrigatória..
        /// </summary>
        public static string CityIsRequired {
            get {
                return ResourceManager.GetString("CityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de produtor encerrado!.
        /// </summary>
        public static string ClosedProducerRegistration {
            get {
                return ResourceManager.GetString("ClosedProducerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Envio para players encerrado..
        /// </summary>
        public static string ClosedSendingToPlayers {
            get {
                return ResourceManager.GetString("ClosedSendingToPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Colaborador deve ter pelo menos um player..
        /// </summary>
        public static string CollaboratorMustHaveAPlayer {
            get {
                return ResourceManager.GetString("CollaboratorMustHaveAPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O colaborador deve ter pelo menos uma produtora..
        /// </summary>
        public static string CollaboratorMustHaveAProducer {
            get {
                return ResourceManager.GetString("CollaboratorMustHaveAProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão Social obrigatório!.
        /// </summary>
        public static string CompanyNameIsRequired {
            get {
                return ResourceManager.GetString("CompanyNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resumo da empresa em inglês é obrigatório..
        /// </summary>
        public static string CompanySummaryInEnglishMandatory {
            get {
                return ResourceManager.GetString("CompanySummaryInEnglishMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resumo da empresa em português é obrigatório..
        /// </summary>
        public static string CompanySummaryInPtBrMandatory {
            get {
                return ResourceManager.GetString("CompanySummaryInPtBrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País inválido.
        /// </summary>
        public static string CountryIsInvalid {
            get {
                return ResourceManager.GetString("CountryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a País obrigatório..
        /// </summary>
        public static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail inválido..
        /// </summary>
        public static string EmailISInvalid {
            get {
                return ResourceManager.GetString("EmailISInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;h4 class=&quot;h4-error-page&quot;&gt;Ocorreu um erro ao acessar essa página.&lt;/h4&gt; 
        ///&lt;h4 class=&quot;h4-error-page&quot;&gt;A equipe Rio2C foi comunicada e atuara para que isso não ocorra novamente. &lt;/h4&gt;
        ///&lt;h4 class=&quot;h4-error-page&quot;&gt;Tente novamente em alguns minutos.&lt;/h4&gt;.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao processar a agenda..
        /// </summary>
        public static string ErrorProcessingAgenda {
            get {
                return ResourceManager.GetString("ErrorProcessingAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao salvar Projeto! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorSavingProject {
            get {
                return ResourceManager.GetString("ErrorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro inesperado ao enviar e-mail..
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;i class=&quot; icon-circle-arrow-left&quot; style=&quot;font-size: 20px&quot;&gt;&lt;/i&gt; Voltar para a página inicial.
        /// </summary>
        public static string ErrorUnexpectedPageLink {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;h4 class=&quot;h4-error-page&quot;&gt;Ocorreu um erro ao acessar essa página.&lt;/h4&gt;
        ///
        ///                &lt;h4 class=&quot;h4-error-page&quot;&gt;
        ///                    Experimente fechar e abrir a janela do seu navegador novamente.
        ///                &lt;/h4&gt;
        ///
        ///              .
        /// </summary>
        public static string ErrorUnexpectedPageText {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar dados do Player &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingPlayerData {
            get {
                return ResourceManager.GetString("ErrorUpdatingPlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar intereses do player &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingPlayerInterests {
            get {
                return ResourceManager.GetString("ErrorUpdatingPlayerInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar dados da Produtora &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingProducerData {
            get {
                return ResourceManager.GetString("ErrorUpdatingProducerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro ao atualizar perfil! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingProfileCheckTheFields {
            get {
                return ResourceManager.GetString("ErrorUpdatingProfileCheckTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ocorreu um erro ao salvar a operação no banco de dados..
        /// </summary>
        public static string ErrorWhileSavingInDataBase {
            get {
                return ResourceManager.GetString("ErrorWhileSavingInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Período de avaliação encerrado.
        /// </summary>
        public static string EvaluationPeriodClosed {
            get {
                return ResourceManager.GetString("EvaluationPeriodClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avaliação salva com sucesso!.
        /// </summary>
        public static string EvaluationSavesSuccessfully {
            get {
                return ResourceManager.GetString("EvaluationSavesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O holding deve ter um nome..
        /// </summary>
        public static string HoldingMustHaveName {
            get {
                return ResourceManager.GetString("HoldingMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Imagem obrigatória.
        /// </summary>
        public static string ImageIsRequired {
            get {
                return ResourceManager.GetString("ImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para inserir uma nova linha use shift+enter..
        /// </summary>
        public static string InsertNewLineUseShiftEnter {
            get {
                return ResourceManager.GetString("InsertNewLineUseShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Interesses incompleto!.
        /// </summary>
        public static string InterestsIncompleteMessage {
            get {
                return ResourceManager.GetString("InterestsIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código Inválido..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A logo deve ter a extensão .png ou .jpeg.
        /// </summary>
        public static string InvalidExtensionPng {
            get {
                return ResourceManager.GetString("InvalidExtensionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato de imagem inválido..
        /// </summary>
        public static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A imagem deve ter entre 1KB e 10MB!.
        /// </summary>
        public static string InvalidResolution {
            get {
                return ResourceManager.GetString("InvalidResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A imagem deve ter entre 1KB  e 10MB!.
        /// </summary>
        public static string InvalidResolutionPlayer {
            get {
                return ResourceManager.GetString("InvalidResolutionPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo em inglês obrigatório..
        /// </summary>
        public static string JobTitleEnIsRequired {
            get {
                return ResourceManager.GetString("JobTitleEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cargo em portugûes obrigatório..
        /// </summary>
        public static string JobTitlePtBrIsRequired {
            get {
                return ResourceManager.GetString("JobTitlePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;hgroup&gt;
        ///    &lt;h1 class=&apos;text-danger&apos;&gt;Bloqueado&lt;/h1&gt;
        ///    &lt;h2 class=&apos;text-danger&apos;&gt;Esta conta foi bloqueada, tente novamente mais tarde.&lt;/h2&gt;
        ///&lt;/hgroup&gt;.
        /// </summary>
        public static string LockOutPage {
            get {
                return ResourceManager.GetString("LockOutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse email não existe, por favor use o mesmo email ao cadastrar na Ticket4You.
        /// </summary>
        public static string LoginByTicket4YouIncorrect {
            get {
                return ResourceManager.GetString("LoginByTicket4YouIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login ou Senha incorretos..
        /// </summary>
        public static string LoginOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("LoginOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;strong&gt;Atenção!&lt;/strong&gt; Para submeter seus projetos é obrigatório o preenchimento do PERFIL e PRODUTORA/EMPRESA..
        /// </summary>
        public static string MandatoryToSubmitYourProject {
            get {
                return ResourceManager.GetString("MandatoryToSubmitYourProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A mensagem é longa demais. Tente encurtá-la ou enviá-la em múltiplas partes..
        /// </summary>
        public static string MessageIsTooLong {
            get {
                return ResourceManager.GetString("MessageIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mini-biografia em inglês é obrigatória..
        /// </summary>
        public static string MiniBioEnIsRequired {
            get {
                return ResourceManager.GetString("MiniBioEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mini-biografia em português é obrigatória..
        /// </summary>
        public static string MiniBioPtBrIsRequired {
            get {
                return ResourceManager.GetString("MiniBioPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O &apos;{0}&apos; deve ter no mínimo &apos;{2}&apos; caracteres..
        /// </summary>
        public static string MinimumNumberOfCharacters {
            get {
                return ResourceManager.GetString("MinimumNumberOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome obrigatório..
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número inválido..
        /// </summary>
        public static string NumberIsInvalid {
            get {
                return ResourceManager.GetString("NumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número obrigatório..
        /// </summary>
        public static string NumberIsRequired {
            get {
                return ResourceManager.GetString("NumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha de confirmação incorreta..
        /// </summary>
        public static string PasswordConfirmationDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dados do player &apos;{0}&apos; atualizados com sucesso!.
        /// </summary>
        public static string PlayerDataSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("PlayerDataSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Player incompleto!.
        /// </summary>
        public static string PlayerIncompleteMessage {
            get {
                return ResourceManager.GetString("PlayerIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Interesses do Player &apos;{0}&apos; atualizados com sucesso!.
        /// </summary>
        public static string PlayerInterestsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("PlayerInterestsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Player não encontrado.
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor clique aqui para logar..
        /// </summary>
        public static string PleaseClickHereToLogin {
            get {
                return ResourceManager.GetString("PleaseClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processando a agenda.
        /// </summary>
        public static string ProcessingAgenda {
            get {
                return ResourceManager.GetString("ProcessingAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A produtora pode ter no máximo {0} projetos salvos..
        /// </summary>
        public static string ProducerMaxProjects {
            get {
                return ResourceManager.GetString("ProducerMaxProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Planos de Produção&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProductionPlanEnIsRequired {
            get {
                return ResourceManager.GetString("ProductionPlanEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Planos de Produção&apos; em português é obrigatório..
        /// </summary>
        public static string ProductionPlanPtBrIsRequired {
            get {
                return ResourceManager.GetString("ProductionPlanPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil incompleto!.
        /// </summary>
        public static string ProfileIncompleteMessage {
            get {
                return ResourceManager.GetString("ProfileIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Perfil atualizado com sucesso! .
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;LogLine&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectLogLineEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectLogLineEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;LogLine&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectLogLinePtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectLogLinePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Está buscando&apos; é obrigatório..
        /// </summary>
        public static string ProjectLookingFor {
            get {
                return ResourceManager.GetString("ProjectLookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Formato&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAFormat {
            get {
                return ResourceManager.GetString("ProjectMustHaveAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Gênero&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAGenre {
            get {
                return ResourceManager.GetString("ProjectMustHaveAGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Plataformas&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAPlatform {
            get {
                return ResourceManager.GetString("ProjectMustHaveAPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Está buscando para este projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveASeeking {
            get {
                return ResourceManager.GetString("ProjectMustHaveASeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Status do projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAStatus {
            get {
                return ResourceManager.GetString("ProjectMustHaveAStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Sub-gênero&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveASubGenre {
            get {
                return ResourceManager.GetString("ProjectMustHaveASubGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Tempo de cada episódio&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveEachEpisodePlayingTime {
            get {
                return ResourceManager.GetString("ProjectMustHaveEachEpisodePlayingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Link de imagem&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveLinksImage {
            get {
                return ResourceManager.GetString("ProjectMustHaveLinksImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Link de teaser&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveLinksTeaser {
            get {
                return ResourceManager.GetString("ProjectMustHaveLinksTeaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Número de episódios&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveNumberOfEpisodes {
            get {
                return ResourceManager.GetString("ProjectMustHaveNumberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Sessões de Pitching&apos; é obrigatória uma resposta..
        /// </summary>
        public static string ProjectMustHavePitching {
            get {
                return ResourceManager.GetString("ProjectMustHavePitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Público alvo&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveTarget {
            get {
                return ResourceManager.GetString("ProjectMustHaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Valor total do projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveTotalValueOfProject {
            get {
                return ResourceManager.GetString("ProjectMustHaveTotalValueOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Valor já arrecadado&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValueAlreadyRaised {
            get {
                return ResourceManager.GetString("ProjectMustHaveValueAlreadyRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Valor por episódio&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValuePerEpisode {
            get {
                return ResourceManager.GetString("ProjectMustHaveValuePerEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Valor que ainda falta&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValueStillNeeded {
            get {
                return ResourceManager.GetString("ProjectMustHaveValueStillNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto não encontrado..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto criado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto apagado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projeto submetido com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ProjectSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Projecto atualizado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Resumo&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectSummaryEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectSummaryEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Resumo&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectSummaryPtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectSummaryPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Título&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectTitleEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectTitleEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;Título&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectTitlePtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectTitlePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Motivo é obrigatorio..
        /// </summary>
        public static string ReasonIsRequired {
            get {
                return ResourceManager.GetString("ReasonIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O motivo deve ter no máximo {0} caracteres..
        /// </summary>
        public static string ReasonMaxLength {
            get {
                return ResourceManager.GetString("ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O motivo deve ter no mínimo {0} caracteres..
        /// </summary>
        public static string ReasonMinLength {
            get {
                return ResourceManager.GetString("ReasonMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastramento de projeto encerrado!.
        /// </summary>
        public static string RegistrationOfClosedProject {
            get {
                return ResourceManager.GetString("RegistrationOfClosedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restrições e especificades em inglês é obrigatório..
        /// </summary>
        public static string RestrictionsSpecificsInEnglishMandatory {
            get {
                return ResourceManager.GetString("RestrictionsSpecificsInEnglishMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restrições e especificades em português é obrigatório..
        /// </summary>
        public static string RestrictionsSpecificsInPtBrMandatory {
            get {
                return ResourceManager.GetString("RestrictionsSpecificsInPtBrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione pelo menos uma opção do grupo {0}..
        /// </summary>
        public static string SelectAtLeastOneGroupOption {
            get {
                return ResourceManager.GetString("SelectAtLeastOneGroupOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado inválido..
        /// </summary>
        public static string StateIsInvalid {
            get {
                return ResourceManager.GetString("StateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado obrigatório..
        /// </summary>
        public static string StateIsRequired {
            get {
                return ResourceManager.GetString("StateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro finalizado com sucesso!.
        /// </summary>
        public static string SuccessfulRegistrationMessage {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de produtora empresa finalizado com sucesso! &lt;a href=&quot;{0}&quot;&gt;Clique aqui&lt;/a&gt; para cadastrar seus projetos..
        /// </summary>
        public static string SuccessfulRegistrationMessageByProducer {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessageByProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro de produtora empresa e de Player finalizado com sucesso! &lt;a href=&quot;{0}&quot;&gt;Clique aqui&lt;/a&gt; para cadastrar seus projetos..
        /// </summary>
        public static string SuccessfulRegistrationMessageByProducerAndPlayer {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessageByProducerAndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string TheFieldIsRequired {
            get {
                return ResourceManager.GetString("TheFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um projeto cadastrado com este título!.
        /// </summary>
        public static string ThereIsalreadyProjectRegisteredWithThisTitle {
            get {
                return ResourceManager.GetString("ThereIsalreadyProjectRegisteredWithThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este projeto já foi enviado para avaliação de players.
        /// </summary>
        public static string ThisProjectHasAlreadyBeenSubmittedForTheEvaluationOfPlayers {
            get {
                return ResourceManager.GetString("ThisProjectHasAlreadyBeenSubmittedForTheEvaluationOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para prosseguir você deve aceitar o Regulamento! | &lt;em class=&apos;english&apos;&gt;To proceed you must accept the terms!&lt;/em&gt;.
        /// </summary>
        public static string ToProceedYouMustAcceptTheTerm {
            get {
                return ResourceManager.GetString("ToProceedYouMustAcceptTheTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome fantasia obrigatório..
        /// </summary>
        public static string TradeNameIsRequired {
            get {
                return ResourceManager.GetString("TradeNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ inválido.
        /// </summary>
        public static string VatNumberIsInvalid {
            get {
                return ResourceManager.GetString("VatNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ obrigatório..
        /// </summary>
        public static string VatNumberIsRequired {
            get {
                return ResourceManager.GetString("VatNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Website obrigatório..
        /// </summary>
        public static string WebSiteIsRequired {
            get {
                return ResourceManager.GetString("WebSiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você pode selecionar no máximo {0} players.
        /// </summary>
        public static string YouCanSelectUpToXPlayers {
            get {
                return ResourceManager.GetString("YouCanSelectUpToXPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você pode enviar para no máximo {0} jogadores..
        /// </summary>
        public static string YouCanSendUpToXPlayers {
            get {
                return ResourceManager.GetString("YouCanSendUpToXPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua senha foi alterada com sucesso!.
        /// </summary>
        public static string YourPasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep obrigatório..
        /// </summary>
        public static string ZipCodeIsRequired {
            get {
                return ResourceManager.GetString("ZipCodeIsRequired", resourceCulture);
            }
        }
    }
}
