//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaRio2C.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlataformaRio2C.Infra.CrossCutting.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaro estar ciente e concordar com as regras e regulamentos acima..
        /// </summary>
        public static string AcceptTermsAndConditions {
            get {
                return ResourceManager.GetString("AcceptTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso negado..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta bloqueada.
        /// </summary>
        public static string AccountLockedOut {
            get {
                return ResourceManager.GetString("AccountLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço obrigatório..
        /// </summary>
        public static string AddressIsRequired {
            get {
                return ResourceManager.GetString("AddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção! Você selecionou somente {0} players de {1} possíveis..
        /// </summary>
        public static string AttentionPossiblePlayersNotSelected {
            get {
                return ResourceManager.GetString("AttentionPossiblePlayersNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja participar do processo de seleção para apresentar esse projeto nas sessões de PITCHING AUDIOVISUAL da Rio2C {0}?.
        /// </summary>
        public static string AudivisualPichingQuestion {
            get {
                return ResourceManager.GetString("AudivisualPichingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do crachá obrigatório..
        /// </summary>
        public static string BadgeIsRequired {
            get {
                return ResourceManager.GetString("BadgeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} para esse projeto..
        /// </summary>
        public static string BuyerEvaluationsAvailableForProject {
            get {
                return ResourceManager.GetString("BuyerEvaluationsAvailableForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2} de um total de {3}..
        /// </summary>
        public static string BuyerEvaluationsSelected {
            get {
                return ResourceManager.GetString("BuyerEvaluationsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível editar um projeto submetido para avaliação de player.
        /// </summary>
        public static string CanNotEditASubmittedProjectForPlayerEvaluation {
            get {
                return ResourceManager.GetString("CanNotEditASubmittedProjectForPlayerEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade inválida..
        /// </summary>
        public static string CityIsInvalid {
            get {
                return ResourceManager.GetString("CityIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade obrigatória..
        /// </summary>
        public static string CityIsRequired {
            get {
                return ResourceManager.GetString("CityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique aqui para alterar sua senha.
        /// </summary>
        public static string ClickHereToChangePassword {
            get {
                return ResourceManager.GetString("ClickHereToChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de produtor encerrado!.
        /// </summary>
        public static string ClosedProducerRegistration {
            get {
                return ResourceManager.GetString("ClosedProducerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envio para players encerrado..
        /// </summary>
        public static string ClosedSendingToPlayers {
            get {
                return ResourceManager.GetString("ClosedSendingToPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador deve ter pelo menos um player..
        /// </summary>
        public static string CollaboratorMustHaveAPlayer {
            get {
                return ResourceManager.GetString("CollaboratorMustHaveAPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O colaborador deve ter pelo menos uma produtora..
        /// </summary>
        public static string CollaboratorMustHaveAProducer {
            get {
                return ResourceManager.GetString("CollaboratorMustHaveAProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social obrigatório!.
        /// </summary>
        public static string CompanyNameIsRequired {
            get {
                return ResourceManager.GetString("CompanyNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo da empresa em inglês é obrigatório..
        /// </summary>
        public static string CompanySummaryInEnglishMandatory {
            get {
                return ResourceManager.GetString("CompanySummaryInEnglishMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumo da empresa em português é obrigatório..
        /// </summary>
        public static string CompanySummaryInPtBrMandatory {
            get {
                return ResourceManager.GetString("CompanySummaryInPtBrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete os dados da sua empresa.
        /// </summary>
        public static string CompleteCompanyrInfo {
            get {
                return ResourceManager.GetString("CompleteCompanyrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete os dados do player {0}.
        /// </summary>
        public static string CompletePlayerInfo {
            get {
                return ResourceManager.GetString("CompletePlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe quais as áreas de interesse do player {0}.
        /// </summary>
        public static string CompletePlayerInterestsFor {
            get {
                return ResourceManager.GetString("CompletePlayerInterestsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete as informações do projeto.
        /// </summary>
        public static string CompleteProjectInfo {
            get {
                return ResourceManager.GetString("CompleteProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete seus dados.
        /// </summary>
        public static string CompleteYourData {
            get {
                return ResourceManager.GetString("CompleteYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete seu cadastro.
        /// </summary>
        public static string CompleteYourRegistration {
            get {
                return ResourceManager.GetString("CompleteYourRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete o cadastro da {0}.
        /// </summary>
        public static string CompleteYourSignup {
            get {
                return ResourceManager.GetString("CompleteYourSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma senha de acesso à conta.
        /// </summary>
        public static string ConfigurePasswordToMyRio2c {
            get {
                return ResourceManager.GetString("ConfigurePasswordToMyRio2c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme e complete seus dados pessoais.
        /// </summary>
        public static string ConfirmAndCompletePersonalInfo {
            get {
                return ResourceManager.GetString("ConfirmAndCompletePersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme e complete seus dados de acesso.
        /// </summary>
        public static string ConfirmAndCompleteYourAccessData {
            get {
                return ResourceManager.GetString("ConfirmAndCompleteYourAccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, confirme para excluir..
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, confirme para excluir da edição {0}..
        /// </summary>
        public static string ConfirmDeleteEdition {
            get {
                return ResourceManager.GetString("ConfirmDeleteEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme para enviar os e-mails de convite.
        /// </summary>
        public static string ConfirmToSendInvitationEmails {
            get {
                return ResourceManager.GetString("ConfirmToSendInvitationEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, corrija os erros do formulário..
        /// </summary>
        public static string CorrectFormValues {
            get {
                return ResourceManager.GetString("CorrectFormValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível criar {0} {1}..
        /// </summary>
        public static string CouldNotCreate {
            get {
                return ResourceManager.GetString("CouldNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível logar na plataforma de talentos..
        /// </summary>
        public static string CouldNotSignInTalentsPlatform {
            get {
                return ResourceManager.GetString("CouldNotSignInTalentsPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País inválido.
        /// </summary>
        public static string CountryIsInvalid {
            get {
                return ResourceManager.GetString("CountryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País obrigatório..
        /// </summary>
        public static string CountryIsRequired {
            get {
                return ResourceManager.GetString("CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está navegando como.
        /// </summary>
        public static string CurrentlyBrowsingAs {
            get {
                return ResourceManager.GetString("CurrentlyBrowsingAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descreve as restrições e/ou especificações sobre o conteúdo desejado..
        /// </summary>
        public static string DescribeRestrictionSpecifics {
            get {
                return ResourceManager.GetString("DescribeRestrictionSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descreva sua mini-biografia.
        /// </summary>
        public static string DescribeYourMiniBiography {
            get {
                return ResourceManager.GetString("DescribeYourMiniBiography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email é utilizado para o login do usuário..
        /// </summary>
        public static string EmailInputMessage {
            get {
                return ResourceManager.GetString("EmailInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        public static string EmailISInvalid {
            get {
                return ResourceManager.GetString("EmailISInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail enviado para {0}..
        /// </summary>
        public static string EmailSentTo {
            get {
                return ResourceManager.GetString("EmailSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} com sucesso..
        /// </summary>
        public static string EntityActionSuccessfull {
            get {
                return ResourceManager.GetString("EntityActionSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe {0} com {1} &apos;{2}&apos;..
        /// </summary>
        public static string EntityExistsWithSameProperty {
            get {
                return ResourceManager.GetString("EntityExistsWithSameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não {1}..
        /// </summary>
        public static string EntityNotAction {
            get {
                return ResourceManager.GetString("EntityNotAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 class=&quot;h4-error-page&quot;&gt;Ocorreu um erro ao acessar essa página.&lt;/h4&gt; 
        ///&lt;h4 class=&quot;h4-error-page&quot;&gt;A equipe Rio2C foi comunicada e atuara para que isso não ocorra novamente. &lt;/h4&gt;
        ///&lt;h4 class=&quot;h4-error-page&quot;&gt;Tente novamente em alguns minutos.&lt;/h4&gt;.
        /// </summary>
        public static string ErrorPage {
            get {
                return ResourceManager.GetString("ErrorPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar a agenda..
        /// </summary>
        public static string ErrorProcessingAgenda {
            get {
                return ResourceManager.GetString("ErrorProcessingAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao salvar Projeto! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorSavingProject {
            get {
                return ResourceManager.GetString("ErrorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro inesperado ao enviar e-mail..
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;i class=&quot; icon-circle-arrow-left&quot; style=&quot;font-size: 20px&quot;&gt;&lt;/i&gt; Voltar para a página inicial.
        /// </summary>
        public static string ErrorUnexpectedPageLink {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 class=&quot;h4-error-page&quot;&gt;Ocorreu um erro ao acessar essa página.&lt;/h4&gt;
        ///
        ///                &lt;h4 class=&quot;h4-error-page&quot;&gt;
        ///                    Experimente fechar e abrir a janela do seu navegador novamente.
        ///                &lt;/h4&gt;
        ///
        ///              .
        /// </summary>
        public static string ErrorUnexpectedPageText {
            get {
                return ResourceManager.GetString("ErrorUnexpectedPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha não pode ser alterada..
        /// </summary>
        public static string ErrorUpdatingPassword {
            get {
                return ResourceManager.GetString("ErrorUpdatingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar dados do Player &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingPlayerData {
            get {
                return ResourceManager.GetString("ErrorUpdatingPlayerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar intereses do player &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingPlayerInterests {
            get {
                return ResourceManager.GetString("ErrorUpdatingPlayerInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar dados da Produtora &apos;{0}&apos;! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingProducerData {
            get {
                return ResourceManager.GetString("ErrorUpdatingProducerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao atualizar perfil! Verifique o preenchimento dos campos!.
        /// </summary>
        public static string ErrorUpdatingProfileCheckTheFields {
            get {
                return ResourceManager.GetString("ErrorUpdatingProfileCheckTheFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao salvar a operação no banco de dados..
        /// </summary>
        public static string ErrorWhileSavingInDataBase {
            get {
                return ResourceManager.GetString("ErrorWhileSavingInDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de avaliação encerrado.
        /// </summary>
        public static string EvaluationPeriodClosed {
            get {
                return ResourceManager.GetString("EvaluationPeriodClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliação salva com sucesso!.
        /// </summary>
        public static string EvaluationSavesSuccessfully {
            get {
                return ResourceManager.GetString("EvaluationSavesSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de financiamento &lt;small&gt;(apenas projetos em desenvolvimento/produção)&lt;/small&gt;.
        /// </summary>
        public static string FundingPlan {
            get {
                return ResourceManager.GetString("FundingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O holding deve ter um nome..
        /// </summary>
        public static string HoldingMustHaveName {
            get {
                return ResourceManager.GetString("HoldingMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se você deseja pular esse passo e registrar sua empresa depois.
        /// </summary>
        public static string IfYouWantToSkipStepAndRegisterLater {
            get {
                return ResourceManager.GetString("IfYouWantToSkipStepAndRegisterLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imagem obrigatória.
        /// </summary>
        public static string ImageIsRequired {
            get {
                return ResourceManager.GetString("ImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe seu endereço.
        /// </summary>
        public static string InformYourAddress {
            get {
                return ResourceManager.GetString("InformYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para inserir uma nova linha use shift+enter..
        /// </summary>
        public static string InsertNewLineUseShiftEnter {
            get {
                return ResourceManager.GetString("InsertNewLineUseShiftEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesses incompleto!.
        /// </summary>
        public static string InterestsIncompleteMessage {
            get {
                return ResourceManager.GetString("InterestsIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Inválido..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido..
        /// </summary>
        public static string InvalidCompanyNumber {
            get {
                return ResourceManager.GetString("InvalidCompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A logo deve ter a extensão .png ou .jpeg.
        /// </summary>
        public static string InvalidExtensionPng {
            get {
                return ResourceManager.GetString("InvalidExtensionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem deve estar no formato jpeg, jpg, gif ou png..
        /// </summary>
        public static string InvalidImage {
            get {
                return ResourceManager.GetString("InvalidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de imagem inválido..
        /// </summary>
        public static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou senha incorretos..
        /// </summary>
        public static string InvalidLoginOrPassword {
            get {
                return ResourceManager.GetString("InvalidLoginOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem deve ter entre 1KB e 10MB!.
        /// </summary>
        public static string InvalidResolution {
            get {
                return ResourceManager.GetString("InvalidResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem deve ter entre 1KB  e 10MB!.
        /// </summary>
        public static string InvalidResolutionPlayer {
            get {
                return ResourceManager.GetString("InvalidResolutionPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível criar o projeto pois essa empresa já atingiu o limite..
        /// </summary>
        public static string IsNotPossibleCreateProjectLimit {
            get {
                return ResourceManager.GetString("IsNotPossibleCreateProjectLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível criar o projeto pois um mesmo ingresso está sendo utilizado em mais de uma empresa..
        /// </summary>
        public static string IsNotPossibleCreateProjectSameTicket {
            get {
                return ResourceManager.GetString("IsNotPossibleCreateProjectSameTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo em inglês obrigatório..
        /// </summary>
        public static string JobTitleEnIsRequired {
            get {
                return ResourceManager.GetString("JobTitleEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo em portugûes obrigatório..
        /// </summary>
        public static string JobTitlePtBrIsRequired {
            get {
                return ResourceManager.GetString("JobTitlePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não serão aceitos links para download, apenas para sites de compartilhamento de imagem ou vídeo, como YouTube e Vimeo..
        /// </summary>
        public static string LinksForDownloadNotAccepted {
            get {
                return ResourceManager.GetString("LinksForDownloadNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta conta foi bloqueada, tente novamente mais tarde..
        /// </summary>
        public static string LockOutPage {
            get {
                return ResourceManager.GetString("LockOutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse email não existe, por favor use o mesmo email ao cadastrar na Ticket4You.
        /// </summary>
        public static string LoginByTicket4YouIncorrect {
            get {
                return ResourceManager.GetString("LoginByTicket4YouIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ou Senha incorretos..
        /// </summary>
        public static string LoginOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("LoginOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Atenção!&lt;/strong&gt; Para submeter seus projetos é obrigatório o preenchimento do PERFIL e PRODUTORA/EMPRESA..
        /// </summary>
        public static string MandatoryToSubmitYourProject {
            get {
                return ResourceManager.GetString("MandatoryToSubmitYourProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contagem de caracteres: %charsTyped%/%charsTotal%.
        /// </summary>
        public static string MaxlengthCounterMessage {
            get {
                return ResourceManager.GetString("MaxlengthCounterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O projeto já atingiu o limite de {0} {1} para avaliação..
        /// </summary>
        public static string MaxProjectBuyersEvaluationsReached {
            get {
                return ResourceManager.GetString("MaxProjectBuyersEvaluationsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não pode selecionar um novo {0} para avaliar o projeto pois todos os grupos de {1} {2} já foram utilizados..
        /// </summary>
        public static string MaxProjectBuyersGroupsReached {
            get {
                return ResourceManager.GetString("MaxProjectBuyersGroupsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mensagem é longa demais. Tente encurtá-la ou enviá-la em múltiplas partes..
        /// </summary>
        public static string MessageIsTooLong {
            get {
                return ResourceManager.GetString("MessageIsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini-biografia em inglês é obrigatória..
        /// </summary>
        public static string MiniBioEnIsRequired {
            get {
                return ResourceManager.GetString("MiniBioEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini-biografia em português é obrigatória..
        /// </summary>
        public static string MiniBioPtBrIsRequired {
            get {
                return ResourceManager.GetString("MiniBioPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O &apos;{0}&apos; deve ter no mínimo &apos;{2}&apos; caracteres..
        /// </summary>
        public static string MinimumNumberOfCharacters {
            get {
                return ResourceManager.GetString("MinimumNumberOfCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome obrigatório..
        /// </summary>
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum ingresso disponível..
        /// </summary>
        public static string NoBadgesAvaiable {
            get {
                return ResourceManager.GetString("NoBadgesAvaiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma conversa encontrada..
        /// </summary>
        public static string NoConversationsFound {
            get {
                return ResourceManager.GetString("NoConversationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número inválido..
        /// </summary>
        public static string NumberIsInvalid {
            get {
                return ResourceManager.GetString("NumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número obrigatório..
        /// </summary>
        public static string NumberIsRequired {
            get {
                return ResourceManager.GetString("NumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibindo {0} a {1} de {2}.
        /// </summary>
        public static string PaginationMessage {
            get {
                return ResourceManager.GetString("PaginationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha de confirmação incorreta..
        /// </summary>
        public static string PasswordConfirmationDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordConfirmationDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do player &apos;{0}&apos; atualizados com sucesso!.
        /// </summary>
        public static string PlayerDataSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("PlayerDataSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player incompleto!.
        /// </summary>
        public static string PlayerIncompleteMessage {
            get {
                return ResourceManager.GetString("PlayerIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados do player {0}.
        /// </summary>
        public static string PlayerInfoFor {
            get {
                return ResourceManager.GetString("PlayerInfoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesses do Player &apos;{0}&apos; atualizados com sucesso!.
        /// </summary>
        public static string PlayerInterestsSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("PlayerInterestsSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player não encontrado.
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamento de Players.
        /// </summary>
        public static string PlayerTerms {
            get {
                return ResourceManager.GetString("PlayerTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor clique aqui para logar..
        /// </summary>
        public static string PleaseClickHereToLogin {
            get {
                return ResourceManager.GetString("PleaseClickHereToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando a agenda.
        /// </summary>
        public static string ProcessingAgenda {
            get {
                return ResourceManager.GetString("ProcessingAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados da produtora.
        /// </summary>
        public static string ProducerInfo {
            get {
                return ResourceManager.GetString("ProducerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A produtora pode ter no máximo {0} projetos salvos..
        /// </summary>
        public static string ProducerMaxProjects {
            get {
                return ResourceManager.GetString("ProducerMaxProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Planos de Produção&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProductionPlanEnIsRequired {
            get {
                return ResourceManager.GetString("ProductionPlanEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Planos de Produção&apos; em português é obrigatório..
        /// </summary>
        public static string ProductionPlanPtBrIsRequired {
            get {
                return ResourceManager.GetString("ProductionPlanPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil incompleto!.
        /// </summary>
        public static string ProfileIncompleteMessage {
            get {
                return ResourceManager.GetString("ProfileIncompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil atualizado com sucesso! .
        /// </summary>
        public static string ProfileUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ProfileUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orçamento do projeto &lt;small&gt;(apenas para projetos em desenvolvimento/produção)&lt;/small&gt;.
        /// </summary>
        public static string ProjectBudget {
            get {
                return ResourceManager.GetString("ProjectBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O projeto está concluído e não pode ser alterado..
        /// </summary>
        public static string ProjectIsFinishedCannotBeUpdated {
            get {
                return ResourceManager.GetString("ProjectIsFinishedCannotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LogLine&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectLogLineEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectLogLineEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;LogLine&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectLogLinePtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectLogLinePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Está buscando&apos; é obrigatório..
        /// </summary>
        public static string ProjectLookingFor {
            get {
                return ResourceManager.GetString("ProjectLookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Formato&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAFormat {
            get {
                return ResourceManager.GetString("ProjectMustHaveAFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Gênero&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAGenre {
            get {
                return ResourceManager.GetString("ProjectMustHaveAGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Plataformas&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAPlatform {
            get {
                return ResourceManager.GetString("ProjectMustHaveAPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Está buscando para este projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveASeeking {
            get {
                return ResourceManager.GetString("ProjectMustHaveASeeking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Status do projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveAStatus {
            get {
                return ResourceManager.GetString("ProjectMustHaveAStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Sub-gênero&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveASubGenre {
            get {
                return ResourceManager.GetString("ProjectMustHaveASubGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Tempo de cada episódio&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveEachEpisodePlayingTime {
            get {
                return ResourceManager.GetString("ProjectMustHaveEachEpisodePlayingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Link de imagem&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveLinksImage {
            get {
                return ResourceManager.GetString("ProjectMustHaveLinksImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Link de teaser&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveLinksTeaser {
            get {
                return ResourceManager.GetString("ProjectMustHaveLinksTeaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Número de episódios&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveNumberOfEpisodes {
            get {
                return ResourceManager.GetString("ProjectMustHaveNumberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Sessões de Pitching&apos; é obrigatória uma resposta..
        /// </summary>
        public static string ProjectMustHavePitching {
            get {
                return ResourceManager.GetString("ProjectMustHavePitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Público alvo&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveTarget {
            get {
                return ResourceManager.GetString("ProjectMustHaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Valor total do projeto&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveTotalValueOfProject {
            get {
                return ResourceManager.GetString("ProjectMustHaveTotalValueOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Valor já arrecadado&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValueAlreadyRaised {
            get {
                return ResourceManager.GetString("ProjectMustHaveValueAlreadyRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Valor por episódio&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValuePerEpisode {
            get {
                return ResourceManager.GetString("ProjectMustHaveValuePerEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Valor que ainda falta&apos; é obrigatório..
        /// </summary>
        public static string ProjectMustHaveValueStillNeeded {
            get {
                return ResourceManager.GetString("ProjectMustHaveValueStillNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto não encontrado..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto salvo mas ainda NÃO enviado para Players. Para enviar o projeto para avaliação selecione os Players e clique em Salvar e Enviar..
        /// </summary>
        public static string ProjectSavedButNotSentToPlayers {
            get {
                return ResourceManager.GetString("ProjectSavedButNotSentToPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período de inscrição não está aberto..
        /// </summary>
        public static string ProjectSubmissionNotOpen {
            get {
                return ResourceManager.GetString("ProjectSubmissionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto criado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyCreated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto apagado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyDeleted {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeto submetido com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ProjectSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projecto atualizado com sucesso!.
        /// </summary>
        public static string ProjectSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ProjectSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Resumo&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectSummaryEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectSummaryEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Resumo&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectSummaryPtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectSummaryPtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Título&apos; em inglês é obrigatório..
        /// </summary>
        public static string ProjectTitleEnIsRequired {
            get {
                return ResourceManager.GetString("ProjectTitleEnIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Título&apos; em português é obrigatório..
        /// </summary>
        public static string ProjectTitlePtBrIsRequired {
            get {
                return ResourceManager.GetString("ProjectTitlePtBrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter entre &apos;{2}&apos; e &apos;{1}&apos; caracteres..
        /// </summary>
        public static string PropertyBetweenLengths {
            get {
                return ResourceManager.GetString("PropertyBetweenLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostaria de disponibilizar algum e-mail para contato entre os participantes da categoria Industry? Este e-mail fará parte somente de uma lista de contatos para download..
        /// </summary>
        public static string PublicEmail {
            get {
                return ResourceManager.GetString("PublicEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo é obrigatorio..
        /// </summary>
        public static string ReasonIsRequired {
            get {
                return ResourceManager.GetString("ReasonIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motivo deve ter no máximo {0} caracteres..
        /// </summary>
        public static string ReasonMaxLength {
            get {
                return ResourceManager.GetString("ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O motivo deve ter no mínimo {0} caracteres..
        /// </summary>
        public static string ReasonMinLength {
            get {
                return ResourceManager.GetString("ReasonMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecionamento para a plataforma de talentos não está ativa..
        /// </summary>
        public static string RedirectTalentsPlatformNotActive {
            get {
                return ResourceManager.GetString("RedirectTalentsPlatformNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastramento de projeto encerrado!.
        /// </summary>
        public static string RegistrationOfClosedProject {
            get {
                return ResourceManager.GetString("RegistrationOfClosedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições e/ou especificações sobre o conteúdo desejado.
        /// </summary>
        public static string RestrictionSpecifics {
            get {
                return ResourceManager.GetString("RestrictionSpecifics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições e especificades em inglês é obrigatório..
        /// </summary>
        public static string RestrictionsSpecificsInEnglishMandatory {
            get {
                return ResourceManager.GetString("RestrictionsSpecificsInEnglishMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições e especificades em português é obrigatório..
        /// </summary>
        public static string RestrictionsSpecificsInPtBrMandatory {
            get {
                return ResourceManager.GetString("RestrictionsSpecificsInPtBrMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma opção..
        /// </summary>
        public static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos uma opção do grupo {0}..
        /// </summary>
        public static string SelectAtLeastOneGroupOption {
            get {
                return ResourceManager.GetString("SelectAtLeastOneGroupOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione pelo menos uma opção do grupo..
        /// </summary>
        public static string SelectAtLeastOneOption {
            get {
                return ResourceManager.GetString("SelectAtLeastOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo está incorreto..
        /// </summary>
        public static string SomethingIsWrong {
            get {
                return ResourceManager.GetString("SomethingIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado inválido..
        /// </summary>
        public static string StateIsInvalid {
            get {
                return ResourceManager.GetString("StateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado obrigatório..
        /// </summary>
        public static string StateIsRequired {
            get {
                return ResourceManager.GetString("StateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passos para inscrição de projeto.
        /// </summary>
        public static string StepsToProjectSubscription {
            get {
                return ResourceManager.GetString("StepsToProjectSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro finalizado com sucesso!.
        /// </summary>
        public static string SuccessfulRegistrationMessage {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de produtora empresa finalizado com sucesso! &lt;a href=&quot;{0}&quot;&gt;Clique aqui&lt;/a&gt; para cadastrar seus projetos..
        /// </summary>
        public static string SuccessfulRegistrationMessageByProducer {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessageByProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de produtora empresa e de Player finalizado com sucesso! &lt;a href=&quot;{0}&quot;&gt;Clique aqui&lt;/a&gt; para cadastrar seus projetos..
        /// </summary>
        public static string SuccessfulRegistrationMessageByProducerAndPlayer {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationMessageByProducerAndPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trocar para.
        /// </summary>
        public static string SwitchTo {
            get {
                return ResourceManager.GetString("SwitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texto em português | texto em inglês.
        /// </summary>
        public static string TextInPortugueseInEnglish {
            get {
                return ResourceManager.GetString("TextInPortugueseInEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo &apos;{0}&apos; é obrigatório..
        /// </summary>
        public static string TheFieldIsRequired {
            get {
                return ResourceManager.GetString("TheFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O projeto deve ter no mínimo 1 {0} para ser concluído..
        /// </summary>
        public static string TheProjectMustHaveOnePlayer {
            get {
                return ResourceManager.GetString("TheProjectMustHaveOnePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um projeto cadastrado com este título!.
        /// </summary>
        public static string ThereIsalreadyProjectRegisteredWithThisTitle {
            get {
                return ResourceManager.GetString("ThereIsalreadyProjectRegisteredWithThisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este projeto já foi enviado para avaliação de players.
        /// </summary>
        public static string ThisProjectHasAlreadyBeenSubmittedForTheEvaluationOfPlayers {
            get {
                return ResourceManager.GetString("ThisProjectHasAlreadyBeenSubmittedForTheEvaluationOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para prosseguir você deve aceitar o regulamento.
        /// </summary>
        public static string ToProceedYouMustAcceptTheTerm {
            get {
                return ResourceManager.GetString("ToProceedYouMustAcceptTheTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome fantasia obrigatório..
        /// </summary>
        public static string TradeNameIsRequired {
            get {
                return ResourceManager.GetString("TradeNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem indefinida..
        /// </summary>
        public static string UndefinedMessage {
            get {
                return ResourceManager.GetString("UndefinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ inválido.
        /// </summary>
        public static string VatNumberIsInvalid {
            get {
                return ResourceManager.GetString("VatNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ obrigatório..
        /// </summary>
        public static string VatNumberIsRequired {
            get {
                return ResourceManager.GetString("VatNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website obrigatório..
        /// </summary>
        public static string WebSiteIsRequired {
            get {
                return ResourceManager.GetString("WebSiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encontramos um erro ao realizar essa operação. Já estamos trabalhando para resolvê-lo..
        /// </summary>
        public static string WeFoundAndError {
            get {
                return ResourceManager.GetString("WeFoundAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua credencial foi adquirida com sucesso!.
        /// </summary>
        public static string WelcomeEmailMessage1 {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário acessar a plataforma &lt;b&gt;MyRio2C&lt;/b&gt; para realizar seu registro e de sua empresa nas Rodadas de Negócios. Por gentileza, clique no botão abaixo e utilize o mesmo endereço de e-mail para fazer o acesso..
        /// </summary>
        public static string WelcomeEmailMessage2 {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em caso de dúvidas, entre em contato com a nossa equipe em:.
        /// </summary>
        public static string WelcomeEmailMessage3 {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENHA FAZER PARTE DO RIO2C.
        /// </summary>
        public static string WelcomeEmailMessage4 {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua oportunidade de viver dias incríveis de aprendizado, negócios, networking e experiências..
        /// </summary>
        public static string WelcomeEmailMessage5 {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode selecionar no máximo {0} players.
        /// </summary>
        public static string YouCanSelectUpToXPlayers {
            get {
                return ResourceManager.GetString("YouCanSelectUpToXPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você pode enviar para no máximo {0} jogadores..
        /// </summary>
        public static string YouCanSendUpToXPlayers {
            get {
                return ResourceManager.GetString("YouCanSendUpToXPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem perfil de administrador..
        /// </summary>
        public static string YouDontHaveAdminProfile {
            get {
                return ResourceManager.GetString("YouDontHaveAdminProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você atingiu o limite de projetos..
        /// </summary>
        public static string YouReachedProjectsLimit {
            get {
                return ResourceManager.GetString("YouReachedProjectsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada com sucesso!.
        /// </summary>
        public static string YourPasswordHasBeenChangedSuccessfully {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você será redirecionado....
        /// </summary>
        public static string YouWillBeRedirected {
            get {
                return ResourceManager.GetString("YouWillBeRedirected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep obrigatório..
        /// </summary>
        public static string ZipCodeIsRequired {
            get {
                return ResourceManager.GetString("ZipCodeIsRequired", resourceCulture);
            }
        }
    }
}
