//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlataformaRio2C.Infra.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlataformaRio2C.Infra.CrossCutting.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições ou especificidades do que está buscando no mercado..
        /// </summary>
        public static string AdditionalInfoDescription {
            get {
                return ResourceManager.GetString("AdditionalInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Após submetê-lo, este projeto não poderá mais ser editado..
        /// </summary>
        public static string AfterSubmitCantChange {
            get {
                return ResourceManager.GetString("AfterSubmitCantChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troca de senha confirmada!.
        /// </summary>
        public static string ChangePasswordConfirmed {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Rede Rio2C está dessincronizada, recarregue a página para sincronizar novamente..
        /// </summary>
        public static string ChatIsOffline {
            get {
                return ResourceManager.GetString("ChatIsOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A programação do Rio2C será divulgada a partir de fevereiro..
        /// </summary>
        public static string ConferenceSoon {
            get {
                return ResourceManager.GetString("ConferenceSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar indicação para avaliação.
        /// </summary>
        public static string ConfirmIndicationForEvaluation {
            get {
                return ResourceManager.GetString("ConfirmIndicationForEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label&gt;Deseja realmente confirmar o interese no projeto &quot;&lt;span&gt;{0}&lt;/span&gt;&quot; para o player &quot;&lt;span&gt;{1}&lt;/span&gt;&quot;&lt;/label&gt;.
        /// </summary>
        public static string DoYouReallyWishAccept {
            get {
                return ResourceManager.GetString("DoYouReallyWishAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;label&gt;Deseja realmente recusar o interese no projeto &quot;&lt;span&gt;{0}&lt;/span&gt;&quot; para o player &quot;&lt;span&gt;{1}&lt;/span&gt;&quot;&lt;/label&gt;.
        /// </summary>
        public static string DoYouReallyWishRefuse {
            get {
                return ResourceManager.GetString("DoYouReallyWishRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-weight: 400;&quot;&gt;Muito obrigada! |&amp;nbsp;&lt;em&gt;Thank you!&lt;/em&gt;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;O Rio2C 2019 foi um enorme sucesso e n&amp;oacute;s agradecemos voc&amp;ecirc; por ser uma parte fundamental desse processo.&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&lt;span style=&quot;color: #0070c0;&quot;&gt;&lt;em&gt;This 2019&amp;rsquo;s Rio2C was a tremendous success and we thank you for being an integral part of it.&lt;/em&gt;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailAgenda {
            get {
                return ResourceManager.GetString("EmailAgenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Para alterar sua senha clique aqui: &lt;br/&gt;&lt;a href=&apos;{0}&apos;&gt;Alterar senha&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        public static string EmailBodyForgotPassword {
            get {
                return ResourceManager.GetString("EmailBodyForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Prezado(a) Sr(a), @{Name},&lt;/p&gt;
        ///&lt;p&gt;Seja bem-vindo(a) ao Rio2C / RioContentMarket!&lt;p/&gt;
        ///&lt;p&gt;Iniciamos as inscrições dos players para as Rodadas de Negócios do &lt;strong&gt;Rio2C / RioContentMarket 2018&lt;/strong&gt;, que acontecerá de &lt;strong&gt;04 a 06 de abril&lt;/strong&gt;, na Cidade das Artes, Barra da Tijuca, Rio de Janeiro.&lt;/p&gt;
        ///&lt;p&gt;Seguem abaixo as instruções para sua inscrição com o link, login e uma senha para acesso. Solicitamos que, por favor, preencha a ficha até o dia &lt;strong&gt;15 de dezembro&lt;/strong&gt;.&lt;/p&gt;
        ///&lt;p&gt;O r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailInviteCollaborator {
            get {
                return ResourceManager.GetString("EmailInviteCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-weight: 400;&quot;&gt;Muito obrigada! |&amp;nbsp;&lt;em&gt;Thank you!&lt;/em&gt;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;O Rio2C 2019 foi um enorme sucesso e n&amp;oacute;s agradecemos voc&amp;ecirc; por ser uma parte fundamental desse processo.&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&lt;span style=&quot;color: #0070c0;&quot;&gt;&lt;em&gt;This 2019&amp;rsquo;s Rio2C was a tremendous success and we thank you for being an integral part of it.&lt;/em&gt;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p style=&quot;font-weight: 400;&quot;&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailProducer {
            get {
                return ResourceManager.GetString("EmailProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plataforma Rio2c - Esqueci minha senha.
        /// </summary>
        public static string EmailSubjectForgotPassword {
            get {
                return ResourceManager.GetString("EmailSubjectForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesse com seu e-mail abaixo..
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Alguma coisa deu errado. Estamos corrigindo o problema!.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer upload de uma foto em formato retrato, colorida, de rosto, recente e com boa qualidade. 
        ///É imprescindível a foto estar em alta resolução, pois será utilizada no catálogo impresso.
        /// </summary>
        public static string FaceFotoCollaboratorProducer {
            get {
                return ResourceManager.GetString("FaceFotoCollaboratorProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fazer upload de uma foto em formato retrato, colorida, de rosto, recente e com &lt;strong&gt;boa qualidade&lt;/strong&gt;. 
        ///É imprescindível a foto estar em alta resolução, pois será utilizada no catálogo impresso .
        /// </summary>
        public static string FacePhoto {
            get {
                return ResourceManager.GetString("FacePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rio2C®, Rio Creative Conference®, RioContentMarket®, PitchingShow®, BrainSpace®, Festivalia®, são marcas registradas. Todos os direitos de uso pertencem a Rio Creative Conferences Ltda., CNPJ: 26.079.220/0001-46. Qualquer uso sem autorização dos nomes ou suas variações é uma violação da lei internacional de registro de marcas..
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Requisição proibida. Desculpe, você não sem privilégios suficientes para acessar essa página ou executar essa requisição..
        /// </summary>
        public static string ForbiddenErrorMessage {
            get {
                return ResourceManager.GetString("ForbiddenErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu sua senha?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para sua conveniência, os projetos podem ser salvos e modificados antes do envio final. Caso o projeto não seja enviado até o dia 17 DE JANEIRO será automaticamente excluído. Uma vez finalizados e enviados para os players, os projetos NÃO PODEM SER ALTERADOS..
        /// </summary>
        public static string ForYourConvenience {
            get {
                return ResourceManager.GetString("ForYourConvenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de financiamento (apenas projetos em desenvolvimento / produção) .
        /// </summary>
        public static string FundingPlan {
            get {
                return ResourceManager.GetString("FundingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Não serão aceitos links para download, só para sites de compartilhamento de imagem ou vídeo, ex: youtube e Vimeo.) .
        /// </summary>
        public static string LinksImageTeaser {
            get {
                return ResourceManager.GetString("LinksImageTeaser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse executivo não tem mini-bio disponível..
        /// </summary>
        public static string NoMinibioAvailable {
            get {
                return ResourceManager.GetString("NoMinibioAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum projeto cadastrado..
        /// </summary>
        public static string NoProjectRegistered {
            get {
                return ResourceManager.GetString("NoProjectRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Você está perdido. Não conseguimos encontrar a página que você estava procurando..
        /// </summary>
        public static string NotFoundErrorMessage {
            get {
                return ResourceManager.GetString("NotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar a seleção. Motivo(s):.
        /// </summary>
        public static string NotPossibleToSaveSelection {
            get {
                return ResourceManager.GetString("NotPossibleToSaveSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sua senha foi alterada..
        /// </summary>
        public static string PasswordWasChanged {
            get {
                return ResourceManager.GetString("PasswordWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi localizada a confirmação de pagamento da sua credencial. Verifique os dados informados e tente novamente..
        /// </summary>
        public static string PaymentNotConfirmed {
            get {
                return ResourceManager.GetString("PaymentNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Projetos disponíveis para avaliação a partir de: 06/01/2020&lt;/li&gt;
        ///&lt;li&gt;Período de avaliação: 06/01 a 21/02/2020&lt;/li&gt;
        ///&lt;li&gt;Agenda das Rodadas de Negócios disponível online a partir de: 23/03/2020&lt;/li&gt;.
        /// </summary>
        public static string PlayerProjectsDates {
            get {
                return ResourceManager.GetString("PlayerProjectsDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player(s) salvo(s) com sucesso.
        /// </summary>
        public static string PlayersSavedSuccess {
            get {
                return ResourceManager.GetString("PlayersSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players selecionados para avaliação deste projeto.
        /// </summary>
        public static string PlayersSelectedForEvaluation {
            get {
                return ResourceManager.GetString("PlayersSelectedForEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Submissão de projetos para as Rodadas de Negócios e Pitching de Audiovisual: 25 de novembro a 23 de dezembro de 2019&lt;/li&gt;
        ///&lt;li&gt;Período de avaliação: 6 de janeiro a 21 de fevereiro de 2020&lt;/li&gt;
        ///&lt;li&gt;Agenda online disponível em: 23 de março de 2020&lt;/li&gt;.
        /// </summary>
        public static string ProducerProjectsDates {
            get {
                return ResourceManager.GetString("ProducerProjectsDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orçamento do projeto (apenas para projetos em desenvolvimento / produção).
        /// </summary>
        public static string ProjectBudget {
            get {
                return ResourceManager.GetString("ProjectBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A avaliação de projetos para as Rodadas de Negócios poderá ser realizada a partir de 2 de janeiro até 23 de fevereiro de 2018..
        /// </summary>
        public static string ProjectSoon {
            get {
                return ResourceManager.GetString("ProjectSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu cadastro já esta confirmado! Para acessar a plataforma Rio2c clique &lt;a href=&apos;http://{0}&apos;&gt;aqui&lt;/a&gt;.
        /// </summary>
        public static string RegisterAlreadyConfirmed {
            get {
                return ResourceManager.GetString("RegisterAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Plataforma Rio2C.
        /// </summary>
        public static string RegisterPlatform {
            get {
                return ResourceManager.GetString("RegisterPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A agenda final das Rodadas de Negócios será divulgada em Março..
        /// </summary>
        public static string ScheduleSoon {
            get {
                return ResourceManager.GetString("ScheduleSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja participar do processo de seleção para apresentar esse projeto nas sessões de PITCHING do Rio2C/RioContentMarket?.
        /// </summary>
        public static string SelectionForPitchingSessions {
            get {
                return ResourceManager.GetString("SelectionForPitchingSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um idioma.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigado por confirmar seu e-mail..
        /// </summary>
        public static string ThanksConfirmation {
            get {
                return ResourceManager.GetString("ThanksConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você foi registrado com sucesso! Verifique seu e-mail com dados de acesso..
        /// </summary>
        public static string VerifyEmailProducerRegistration {
            get {
                return ResourceManager.GetString("VerifyEmailProducerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor verifique seu e-mail para redefinir sua senha..
        /// </summary>
        public static string VerifyYourEmail {
            get {
                return ResourceManager.GetString("VerifyYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aguarde estamos processando a seleção de player.
        /// </summary>
        public static string WaitProcessingPlayerSelection {
            get {
                return ResourceManager.GetString("WaitProcessingPlayerSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;news-message-content&quot;&gt;
        ///            &lt;p&gt;Essa é uma área exclusiva para players.&lt;/p&gt;
        ///                 
        ///             &lt;p&gt;Aqui, você poderá manter as suas informações pessoais e da sua empresa atualizadas, receber e avaliar os projetos que deseja atender nas Rodadas de Negócios, ver a sua agenda de palestras e se comunicar com outros players e produtoras através da Rio2C Net.
        ///            &lt;/p&gt;
        ///
        ///            &lt;p&gt;
        ///                Fique atento ao cronograma abaixo, para não perder nenhuma informação  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeContent {
            get {
                return ResourceManager.GetString("WelcomeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;news-message-content&quot;&gt;
        ///            &lt;p&gt;Essa é uma área exclusiva para produtoras.&lt;/p&gt;
        ///                 
        ///             &lt;p&gt;Aqui, você poderá manter as suas informações pessoais e da sua empresa atualizadas, cadastrar e submeter os projetos.
        ///            &lt;/p&gt;
        ///          
        ///            &lt;p&gt;Atenciosamente,&lt;br /&gt;
        ///                Equipe Rio2C&lt;/p&gt;
        ///        &lt;/div&gt;
        ///
        ///        &lt;div class=&quot;news-message-contact clearfix&quot;&gt;
        ///            &lt;p class=&quot;pull-left&quot;&gt;
        ///                Fernando Continentino&lt;br /&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeContentProducer {
            get {
                return ResourceManager.GetString("WelcomeContentProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O maior evento de criatividade e inovação da América Latina..
        /// </summary>
        public static string WelcomeLogin {
            get {
                return ResourceManager.GetString("WelcomeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Olá @{Name},&lt;/p&gt;
        ///&lt;p&gt;Seja bem vindo(a) a Plataforma Rio2C.&lt;/p&gt;
        ///&lt;p&gt;Para acessar a Plataforma Rio2C acesse o site: @{UrlSite}&lt;/p&gt;
        ///&lt;p&gt;Usuário: @{Email}&lt;/p&gt;
        ///&lt;p&gt;Senha: @{Password}&lt;/p&gt;.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Olá @{Name},&lt;/p&gt;
        ///&lt;p&gt;Seja bem vindo(a) a Plataforma Rio2C.&lt;/p&gt;
        ///&lt;p&gt;Seu cadastro como Produtor(a) foi confirmado.&lt;/p&gt;
        ///&lt;p&gt;Acesse Plataforma Rio2C no link: @{UrlSite} com seus dados de acesso.&lt;/p&gt;.
        /// </summary>
        public static string WelcomeTextProducer {
            get {
                return ResourceManager.GetString("WelcomeTextProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participará no processo de seleção das sessões PITCHING no Rio2C / RioContentMarket.
        /// </summary>
        public static string WillTakePartInPitching {
            get {
                return ResourceManager.GetString("WillTakePartInPitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gostaria de submeter o projeto &quot;{0}&quot; para avaliação destes players?.
        /// </summary>
        public static string WouldYouLikeToSubmitProject {
            get {
                return ResourceManager.GetString("WouldYouLikeToSubmitProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está acessando como.
        /// </summary>
        public static string YouAreCurrentlyBrowsingAs {
            get {
                return ResourceManager.GetString("YouAreCurrentlyBrowsingAs", resourceCulture);
            }
        }
    }
}
