// <auto-generated />
namespace PlataformaRio2C.Infra.Data.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class DeleteStatesAndCountriesManuallyRecordeds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeleteStatesAndCountriesManuallyRecordeds));
        
        string IMigrationMetadata.Id
        {
            get { return "202505061816302_DeleteStatesAndCountriesManuallyRecordeds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
